import type { Chapter, Project } from './types';

export const MEMBERS = [
  { name: 'Alex', initial: 'A', color: 'rust', email: 'alex@score.co.kr', role: 'PM' as const, isMe: true },
  { name: 'Chris', initial: 'C', color: 'navy', email: 'chris@score.co.kr', role: '작성자' as const },
  { name: 'Jamie', initial: 'J', color: 'forest', email: 'jamie@score.co.kr', role: '작성자' as const },
  { name: 'Sam', initial: 'S', color: 'amber', email: 'sam@score.co.kr', role: '작성자' as const },
];

export const SAMPLE_CHAPTERS: Chapter[] = [
  { id: 'ch1', name: '도입 배경 및 필요성', parentId: null, order: 1, status: 'done',
    assignee: 'Ryan', assigneeInitial: 'R', assigneeColor: 'rust',
    intent: '외환 규제 변화로 인한 수동 프로세스 한계를 수치로 제시하고 AI 도입 불가피성을 납득시켜야 함.',
    rfp: ['RFP 1.2'],
    pptVersions: [{ name: '도입배경_v2.pptx', size: '1.8MB', version: 2, uploader: 'Ryan', date: '2일 전' },
                  { name: '도입배경_v1.pptx', size: '1.5MB', version: 1, uploader: 'Ryan', date: '5일 전' }],
    slides: [{ title: '도입 배경 및 필요성', sub: '현행 프로세스 한계 분석', color: 'navy' }, { title: '규제 환경 변화 분석', sub: '금융감독원 동향', color: 'navy' }, { title: '현행 업무 프로세스 한계', sub: 'As-Is 분석', color: 'navy' }],
    attachments: [], text: '최근 외환거래 규정의 복잡도 증가와 금융감독원의 컴플라이언스 강화 기조로 인해, 현행 수동 기반 외환업무 처리 방식의 한계가 명확해지고 있습니다.' },
  { id: 'ch1-1', name: '현황 분석', parentId: 'ch1', order: 1, status: 'done',
    assignee: 'Ryan', assigneeInitial: 'R', assigneeColor: 'rust',
    intent: '현행 수동 처리 방식의 오류율 데이터를 중심으로 현황 문제를 수치로 제시.',
    rfp: ['RFP 1.1'],
    pptVersions: [{ name: '현황분석_v1.pptx', size: '1.2MB', version: 1, uploader: 'Ryan', date: '어제' }],
    slides: [{ title: '현황 분석', sub: '오류율 & 처리 건수', color: 'navy' }, { title: '경쟁사 현황', sub: '도입 사례 비교', color: 'navy' }],
    attachments: [], text: '우리은행의 외환 처리 건수는 연간 약 120만 건으로, 처리 오류율은 업계 평균 대비 1.4배 높은 수준입니다.' },
  { id: 'ch1-2', name: '도입 필요성', parentId: 'ch1', order: 2, status: 'review',
    assignee: 'Sam', assigneeInitial: 'S', assigneeColor: 'amber',
    intent: '규제 환경 변화와 경쟁사 도입 현황을 근거로 도입 불가피성 서술.',
    rfp: ['RFP 1.2'], pptVersions: [], slides: [], attachments: [], text: '' },
  { id: 'ch2', name: '운영 방안', parentId: null, order: 2, status: 'review',
    assignee: 'Jamie', assigneeInitial: 'J', assigneeColor: 'forest',
    intent: '담당자 역할·예외 처리 포함한 운영 체계 제시. 기술 설명 아닌 실제 운영 관점.',
    rfp: ['RFP 3.1'],
    pptVersions: [{ name: '운영방안_v2.pptx', size: '1.8MB', version: 2, uploader: 'Jamie', date: '오늘' },
                  { name: '운영방안_v1.pptx', size: '1.5MB', version: 1, uploader: 'Jamie', date: '3일 전' }],
    slides: [{ title: '운영 방안 개요', sub: '조직 및 프로세스', color: 'forest' }, { title: '운영 조직 구성', sub: '역할 및 책임', color: 'forest' }, { title: '예외 처리 프로세스', sub: 'AI 플래그 대응', color: 'forest' }, { title: 'SLA 및 장애 대응', sub: '24시간 운영 체계', color: 'forest' }],
    attachments: [], text: 'AI 컴플라이언스 시스템 도입 후 운영은 기존 외환업무팀 조직 체계를 유지하면서 AI 운영 전담 인력 2명을 추가 배치하는 방식으로 진행됩니다.' },
  { id: 'ch3', name: '시스템 아키텍처', parentId: null, order: 3, status: 'wip',
    assignee: 'Sam', assigneeInitial: 'S', assigneeColor: 'amber',
    intent: 'DCS/BDC 연동 구조 명확히. 신규 구축 아닌 통합임을 강조할 것.',
    rfp: ['RFP 2.1', 'RFP 2.3'],
    pptVersions: [{ name: '아키텍처_v2.pptx', size: '2.1MB', version: 2, uploader: 'Sam', date: '오늘' },
                  { name: '아키텍처_v1.pptx', size: '1.9MB', version: 1, uploader: 'Sam', date: '3일 전' }],
    slides: [],
    attachments: [{ name: '시스템_다이어그램.png', size: '0.8MB', date: '어제', icon: '🖼️' }],
    text: '에스코어의 AI 컴플라이언스 솔루션은 기존 우리은행 DCS 및 BDC 인프라와의 완전한 통합을 전제로 설계되었습니다.' },
  { id: 'ch3-1', name: '데이터 흐름', parentId: 'ch3', order: 1, status: 'wip',
    assignee: 'Sam', assigneeInitial: 'S', assigneeColor: 'amber',
    intent: '데이터 파이프라인의 각 단계별 처리 흐름을 다이어그램과 함께 설명.',
    rfp: ['RFP 2.1'], pptVersions: [], slides: [], attachments: [], text: '' },
  { id: 'ch3-2', name: '보안 아키텍처', parentId: 'ch3', order: 2, status: 'todo',
    assignee: null, assigneeInitial: null, assigneeColor: null,
    intent: '', rfp: ['RFP 2.3'], pptVersions: [], slides: [], attachments: [], text: '' },
  { id: 'ch4', name: '보안 및 컴플라이언스', parentId: null, order: 4, status: 'todo',
    assignee: 'Alex', assigneeInitial: 'A', assigneeColor: 'rust',
    intent: '금융보안원 기준 항목별 충족 명시. 체크리스트처럼 읽힐 것.',
    rfp: ['RFP 4.2', 'RFP 4.3'], pptVersions: [], slides: [], attachments: [], text: '' },
  { id: 'ch5', name: '추진 일정', parentId: null, order: 5, status: 'todo',
    assignee: null, assigneeInitial: null, assigneeColor: null,
    intent: '', rfp: [], pptVersions: [], slides: [], attachments: [], text: '' },
  { id: 'ch6', name: '기대 효과', parentId: null, order: 6, status: 'todo',
    assignee: 'Ryan', assigneeInitial: 'R', assigneeColor: 'rust',
    intent: '정량 수치 중심. 업무시간 절감률·오류율 감소 KPI 제시로 ROI 납득.',
    rfp: ['RFP 2.4'], pptVersions: [], slides: [], attachments: [], text: '' },
];

export const INITIAL_PROJECTS: Project[] = [
  { id: 'p1', name: '우리은행 AI 스마트 컴플라이언스', client: '우리은행 · 디지털전략본부',
    emoji: '🏦', progress: 42, deadline: '2025.04.30',
    members: MEMBERS, chapters: SAMPLE_CHAPTERS },
  { id: 'p2', name: 'SK케미칼 품질관리 포털 구축', client: 'SK케미칼 · IT혁신팀',
    emoji: '🏭', progress: 78, deadline: '2025.05.15',
    members: MEMBERS.slice(0, 2),
    chapters: [] },
  { id: 'p3', name: '국민은행 차세대 뱅킹 플랫폼', client: '국민은행 · 디지털혁신본부',
    emoji: '🏛', progress: 15, deadline: '2025.06.20',
    members: MEMBERS.slice(0, 3),
    chapters: [] },
];

export const TEMPLATES = [
  { name: '일반 제안서', chapters: ['도입 배경 및 필요성', '솔루션 개요', '운영 방안', '기대 효과'] },
  { name: 'SI/개발 제안서', chapters: ['현황 분석', '요구사항 분석', '시스템 아키텍처', '구현 계획', '추진 일정', '기대 효과'] },
  { name: 'AI 솔루션 제안서', chapters: ['도입 배경', 'AI 모델 설계', '시스템 아키텍처', '보안 및 컴플라이언스', '운영 방안', '기대 효과'] },
];
